name: Release artifacts
on:
  workflow_dispatch:
    inputs:
      workflow-run-id:
        description: 'Workflow run to download the artifacts'
        required: true
      artifact-name-pattern:
        description: 'Pattern to match artifact name'
        required: true

jobs:  
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create builds directory  
        run: mkdir builds

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: builds
          run-id: ${{ inputs.workflow-run-id }}
          pattern: ${{ inputs.artifact-name-pattern }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install cloudsmith-cli
        run: pip install --upgrade cloudsmith-cli

      - name: Release
        run: bash scripts/release.sh
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
          GITHUB_MESSAGE: ${{ github.event.head_commit.message }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_WORKSPACE: ${{ github.workspace }}
